{
 "title": "Database monitoring",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "table",
    "query": {
     "query": "label_values(app_database_queries_total,table)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Table overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total queries",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(app_database_queries_total{table=\"$table\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total success",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(app_database_queries_total{table=\"$table\", status=\"success\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total  failure",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(app_database_queries_total{table=\"$table\", status=\"error\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Query success by operation",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "app_database_queries_total{table=\"$table\", status=\"success\"}",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Query failure by operation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "app_database_queries_total{table=\"$table\", status=\"error\"}",
     "legendFormat": "{{operation}}"
    }
   ]
  }
 ]
}