{
 "title": "General Dashboard for Web Application",
 "tags": [
  "backend",
  "frontend"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Users", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    { "expr": "app_users_active_per_day", "legendFormat": "total_active_users" }
   ]
  },
  {
   "title": "Total Users",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "app_users_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "New users per day",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 9 },
   "targets": [
    { "expr": "app_users_new_per_day", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Friendships",
   "type": "stat",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "app_friendships_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Friendships Per User",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 11, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "app_friendships_per_user", "legendFormat": "__auto" }
   ]
  },
  { "title": "Chats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Messages per user",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "app_messages_per_user", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Messages",
   "type": "stat",
   "gridPos": { "h": 6, "w": 11, "x": 12, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "app_messages_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Messages per day",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 29 },
   "targets": [
    { "expr": "app_messages_per_day", "legendFormat": "total" }
   ]
  },
  { "title": "Games", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Total Games Played",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "app_pong_matches_total + app_tictactoe_matches_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Games played over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 7, "y": 36 },
   "targets": [
    { "expr": "app_pong_matches_total", "legendFormat": "pongMatches" },
    { "expr": "app_tictactoe_matches_total", "legendFormat": "tic tac toe" }
   ]
  }
 ]
}